### PR TITLE
fix: #212 UI Redesign - Mobile - Settings

### LINKED ISSUE #212: UI Redesign - Mobile - Settings
**Description**
The task is to implement the new design for the settings menu in the mobile app. 

**Assets and Design Screens**
All assets and design screens have already been created.

- The Figma design can be found here https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=2%3A3
- The Assets required can be found here https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=0%3A1

For help with using Figma please watch this short tutorial video
https://user-images.githubusercontent.com/69275762/192322842-2ac40f88-c396-4a66-933b-3c8abae516c3.mov

**Additional context**
This work should be done on the UI_Redesign branch https://github.com/atsign-foundation/atmosphere_pro/tree/ui_redesign

### PR DESCRIPTION
**Pull request by Chandram-Dutta**
**- What I did**
- Added the new font(Inter) for the UI Redesign and updated the same in pubspec.yaml and app.dart
- Added the new background for mobile as found on Figma and updated the same in images.dart
- Fixes #212

**- How I did it**
-Explained in "What I did"
-Followed the code style and present conventions used in the app

**- How to verify it**
-The changes are quite easy to verify by looking in the code. It doesnt break anything in the app.

**- Description for the changelog**
-The changes will make it easier for contributors to contribute in the hacktoberfest.

### CODE REVIEW

**Comment by Chandram-Dutta** [comment]
@ksanty  The latest commit in this PR fixes the Hacktoberfest issue of #212!

File: lib/screens/settings/settings_screen.dart [hunk 1]
```diff
@@ -0,0 +1,207 @@
+import 'package:at_backupkey_flutter/widgets/backup_key_widget.dart';
+import 'package:at_client_mobile/at_client_mobile.dart';
+import 'package:at_common_flutter/services/size_config.dart';
+import 'package:atsign_atmosphere_pro/screens/settings/widgets/settings_buttons.dart';
+import 'package:atsign_atmosphere_pro/utils/colors.dart';
+import 'package:flutter/material.dart';
+import 'package:package_info_plus/package_info_plus.dart';
+import 'package:url_launcher/url_launcher.dart';
+
+import '../../routes/route_names.dart';
```
Comment (nitesh2599) [inline lib/screens/settings/settings_screen.dart:10]: @Chandram-Dutta The changes look good, but it would be great if we use the same import conventions throughout.

Can you please change all the imports to use `import 'package:atsign_atmosphere_pro/.....` this pattern.

Comment (Chandram-Dutta) [reply lib/screens/settings/settings_screen.dart:10]: Will do it today

**Comment by nitesh2599** [comment]
@tinashe404 The code looks fine.

**Comment by tinashe404** [comment]
@Chandram-Dutta This PR will be merged. You qualified for an Atsign prize. Please could you send an email to hacktoberfest@atsign.com with a screenshot of the PR approval email. Thanks!
